const GAME_CYCLE_INIT = "INIT";
const GAME_CYCLE_BET = "BET";
const GAME_CYCLE_LOSS = "LOSS";
const GAME_CYCLE_CHECKOUT = "CHECKOUT";
const GAME_CYCLE_WIN = "WIN";

export {
  GAME_CYCLE_INIT,
  GAME_CYCLE_BET,
  GAME_CYCLE_LOSS,
  GAME_CYCLE_CHECKOUT,
  GAME_CYCLE_WIN,
};
